### ISSUE TITLE
Request for enhancement

### ISSUE THREAD

**Issue by lyazide** [mgrl/photobooth-imageserver#6]
Hi, do you think we can add a fonction to connect the WLED directly to the RPI GPIO?

[](https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage)

**Comment by mgrl** [comment]
Need to clarify:
WLED is a firmware for ESP modules.
WS281xx are addressable LEDs.
WS281xx can be connected directly to the RPI GPIO.
Using it directly comes with problems:

- need to disable audio on rpi
- need sudo for server to run, because
- very low level bitbanging of the data sent to the WS281xx leds.

For this reason and to be platform independent, I removed internal GPIO support for WS Leds.
Any of the cheapest ESP modules from amazon will work. Just connect via USB to RPI and setup your animations directly on the ESP.
